# Dynamic port for Render (local me 8075 chalega)
server.port=${PORT:8075}

# MongoDB URI from environment variable (secure method)
spring.data.mongodb.uri=${MONGO_URI}

# Database name
spring.data.mongodb.database=googleformdb